site_name: Kubernetes Examples
nav:
  - Home: index.md
  - Deployments:
      - deployments/deploy-grafana.md
      - deployments/deploy-tomcat.md
      - deployments/deploy-node.md
  - Services and Networking:
      - services-and-networking/example1.md
theme:
  name: material
  highlight: dracula # Code highlighting theme
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
