name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - "*"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force --remote-branch ${GITHUB_REF_NAME}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
